	# Compiler + flags
	CXX      := g++
	CXXFLAGS := -I src/include -std=c++17
	LDFLAGS  := -L src/lib -lmingw32 -lSDL3main -lSDL3
	
	# Source files
	SRC := \
	Actor.cpp \
	Camera.cpp \
	Chunk.cpp \
	ChunkManager.cpp \
	TileMap.cpp \
	Engine.cpp \
	JumpingState.cpp \
	NeutralState.cpp \
	Player.cpp \
	PlayerModule.cpp \
	RenderModule.cpp \
	StateMachine.cpp \
	TilesetLoader.cpp \
	main.cpp
	
	OBJ := $(SRC:.cpp=.o)
	BIN := Game.exe
	
	.PHONY: all clean
	
	all: $(BIN)
	
	$(BIN): $(OBJ)
	$(CXX) -o $@ $^ $(LDFLAGS)
	
	%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
	
	clean:
	rm -f $(OBJ) $(BIN)